# Generated by Django 3.2.8 on 2021-10-15 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instruments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('symbol', models.CharField(max_length=10)),
                ('date', models.DateField()),
                ('isEnabled', models.BooleanField()),
                ('type', models.CharField(max_length=20)),
                ('iexID', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Portfolios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('holding_value', models.FloatField()),
                ('total_profit_loss', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Trades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volume', models.PositiveIntegerField()),
                ('buy_value', models.PositiveIntegerField()),
                ('sell_value', models.PositiveIntegerField()),
                ('profit_loss', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='trading.instruments')),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='trading.portfolios')),
            ],
        ),
    ]
