# Generated by Django 3.2.8 on 2021-10-18 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0002_rename_iexid_instruments_iexid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='instruments',
            options={'verbose_name': 'Instrument', 'verbose_name_plural': 'Instruments'},
        ),
        migrations.AlterModelOptions(
            name='portfolios',
            options={'verbose_name': 'Portfolio', 'verbose_name_plural': 'Portfolios'},
        ),
        migrations.AlterModelOptions(
            name='trades',
            options={'verbose_name': 'Trade', 'verbose_name_plural': 'Trades'},
        ),
        migrations.AlterField(
            model_name='portfolios',
            name='holding_value',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='portfolios',
            name='total_profit_loss',
            field=models.FloatField(null=True),
        ),
    ]
