# Generated by Django 3.2.8 on 2021-10-19 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0004_auto_20211018_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instruments',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='instruments',
            name='iexId',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='instruments',
            name='isEnabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='instruments',
            name='type',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
