# Generated by Django 3.2.8 on 2021-10-19 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0006_alter_trades_buy_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolios',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='portfolios',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
